#!/bin/csh

\rm .gmt*
gmtset MEASURE_UNIT INCH
gmtset ANOT_FONT_SIZE 10
gmtset HEADER_FONT_SIZE 10
gmtset HEADER_OFFSET 0.5c
gmtset LABEL_FONT_SIZE 10
gmtset COLOR_NAN  200/200/200
setenv LC_NUMERIC C.UTF-8

set cfg = config_forward.dat

set pick_file = picks_synth

# construct input file
awk '{print "STAN", $1, $2, 0, $3, 0, $2, 0, $3, 0, $2, $3, 0.01}' synth_model >! res.dat
awk '{print "EQ",$1, $2, $3, $4,0,0,0,0,0,0,0}' quakes.dat >> res.dat
awk '{print "EZ",$1, $2, $3, $4,0,0,0,0,0,0,0}' quakes.dat >> res.dat
awk '{print "RES", $1, $5, $6, 0, 0}' stations.dat >> res.dat
echo "NOISE 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1"  >> res.dat


# forward
./fw $cfg res.dat $pick_file >! predictions

paste $pick_file predictions | awk '{if ($1=="#") {print $1, $2, $3, $4, $5;} else {print $1, $2, $3, $4, $5, $6, $14, $8}}' >! synths_wo_noise


# add gaussian noise: P0 0.05 P1 0.1 P2 0.15 P3 0.2 S0 0.175 S1 0.225 S2 0.275 S3 0.325
set rms = 0.10
set rseed = 33
awk 'BEGIN {srand(1*"'$rseed'")}{do {x1=2.0*rand()-1; x2=2.0*rand()-1; s=x1*x1+x2*x2;} while ((s>1) || (s==0)); rnd=x1*sqrt(-2.0*log(s)/s); if ($1=="#") {print $0;} else {f=0; if ($3=="S") {f=1;} print $1, $2, $3, $4, $5, $6, $7+rnd*"'$rms'"*(($8+1+2.5*f)/4)*2, $8}}' synths_wo_noise >!  synths_with_noise


# check
./fw $cfg res.dat synths_wo_noise >! t1
./fw $cfg res.dat synths_with_noise >! t1
\cp synths_with_noise picks

# clean-up
\rm res.dat synths_with_noise synths_wo_noise t1


