#!/bin/csh

\rm .gmt*
gmtset MEASURE_UNIT INCH
gmtset ANOT_FONT_SIZE 10
gmtset HEADER_FONT_SIZE 10
gmtset HEADER_OFFSET 0.5c
gmtset LABEL_FONT_SIZE 10
gmtset COLOR_NAN  200/200/200


set d    = `awk '{if (NR==1) print $1}' config_eqx.dat`
set nz   = `awk '{if (NR==4) print $1}' config_eqx.dat`
set zmin = `awk '{if (NR==7) print $1}' config_eqx.dat`
set zmax = `echo $zmin $nz $d | awk '{print $1+$2*$3}'`

set nx   = `awk '{if (NR==2) print $1}' config_eqx.dat`
set xmin = `awk '{if (NR==5) print $1}' config_eqx.dat`
set xmax = `echo $xmin $nx $d | awk '{print $1+$2*$3}'`

set ny   = `awk '{if (NR==3) print $1}' config_eqx.dat`
set ymin = `awk '{if (NR==6) print $1}' config_eqx.dat`
set ymax = `echo $ymin $ny $d | awk '{print $1+$2*$3}'`


awk '{if ($1=="RES") print $2, $3, $4}' resmcnx.dat >! t1

awk '{if ($1!="#") print $1, $2, $4, $5, $6}' picks | sort | uniq >! rec.dat


egrep EZ resmcnx.dat >! resmcna.tmp


# x-y
psbasemap -JX4/4 -R$xmin/$xmax/$ymin/$ymax -B50f10NWse -K -X0.7 -Y2.9 >! eq.ps

paste t1 rec.dat | awk '{print $6, $7}' | psxy -JX -R -Sc0.05 -Glightblue -K -O >> eq.ps
paste t1 rec.dat | awk '{if ($2>0) print $6, $7, $2*0.25}' | psxy -JX -R -Sc -K -O >> eq.ps
paste t1 rec.dat | awk '{if ($2<0) print $6, $7, -$2*0.25}' | psxy -JX -R -S+  -K -O >> eq.ps


awk '{print $3, $4}' resmcna.tmp | psxy -JX -R -Sc0.04 -Gred -K -O >> eq.ps
awk '{print $3, $4, $6/2.0, $7/2.0}' resmcna.tmp | psxy -JX -R -Sc0.001 -Exy0.01 -K -O >> eq.ps

awk '{print $2, $3}' quakes.dat | psxy -JX -R -Sc0.01 -Gblack -K -O >> eq.ps

#z-y
psbasemap -JX2.5/4 -R$zmin/$zmax/$ymin/$ymax -B20f10g1000/50f10:"`pwd`":sENw -K -O -X4 >> eq.ps
awk '{print $5, $4}' resmcna.tmp | psxy -JX -R -Sc0.04 -Gred -K -O >> eq.ps
awk '{print $5, $4, $8/2.0, $7/2.0}' resmcna.tmp | psxy -JX -R -Sc0.001 -Exy0.01 -K -O >> eq.ps
awk '{print $4, $3}' quakes.dat | psxy -JX -R -Sc0.01 -Gblack -K -O >> eq.ps


#x-z
psbasemap -JX4/-2.5 -R$xmin/$xmax/$zmin/$zmax -B50f10/20f10g1000Wsne -K -O -X-4 -Y-2.5 >> eq.ps
awk '{print $3, $5}' resmcna.tmp | psxy -JX -R -Sc0.04 -Gred -K -O >> eq.ps
awk '{print $3, $5, $6/2.0, $8/2.0}' resmcna.tmp | psxy -JX -R -Sc0.001 -Exy0.01 -K -O >> eq.ps
awk '{print $2, $4}' quakes.dat | psxy -JX -R -Sc0.01 -Gblack -K -O >> eq.ps



echo 0 0 | psxy -JX -R -B0 -Sc0.001 -O >> eq.ps

\rm t1 rec.dat resmcna.tmp



